apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: investoriq-ns
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: asharamir/investoriq-backend:1.0
          imagePullPolicy: Always
