apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  namespace: investoriq-ns
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080

---

apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: investoriq-ns
spec:
  type: ClusterIP
  selector:
    app: backend
  ports:
    - port: 5000
      targetPort: 5000
